version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - codebuild/do_nothing.sh
  build:
    commands:
      - codebuild/build.sh
  post_build:
    commands:
      - codebuild/do_nothing.sh
