version: "3"
services:
  peanuts-app:
    image: "rotwatsb/peanuts:latest"
    ports:
      - "5000:5000"
    environment:
      - RPC_USER
      - RPC_PASSWORD
      - RPC_BITCOIN_HOST
      - FLASK_APP=app
      - FLASK_ENV
