version: "3"
services:
  web:
    image: "rotwatsb/peanuts:latest"
    ports:
      - "5000:5000"
    environment:
      - RPC_USER
      - RPC_PASSWORD
      - FLASK_APP=app
      - FLASK_ENV
  bitcoin:
    image: "rotwatsb/bitcoin-service:latest"
    ports:
      - "8333:8333"
    environment:
      - RPC_USER
      - RPC_PASSWORD
    volumes:
      - peanuts:/data
volumes:
  peanuts:
    driver: rexray/ebs
    driver_opts:
      size: 250
