version: "3"
services:
  peanuts-app:
    build: .
    depends_on:
      - btcwrapp
    networks:
      - test-network
    ports:
      - "5000:5000"
    environment:
      - ENV
    command: ["bash", "/project/docker/run_tests.sh"]
  btcwrapp:
    image: "rotwatsb/btcwrapp:latest"
    depends_on:
      - bitcoin-service
    networks:
      - test-network
    ports:
      - "8000:8000"
    environment:
      - RPC_USER
      - RPC_PASSWORD
      - ENV
  bitcoin-service:
    image: "rotwatsb/bitcoin-service:latest"
    networks:
      - test-network
    ports:
      - "8333:8333"
    environment:
      - RPC_USER
      - RPC_PASSWORD
      - RPC_CLIENT_HOST
    volumes:
      - bitcoindata:/data
volumes:
  bitcoindata:
networks:
  test-network:
    driver: bridge
