#!/bin/bash

# run as: ./run_peanuts.sh RPC_USER RPC_PASSWORD ALLOWED_CONTAINER BITCOIN_CONTAINER
RPC_USER=$1
RPC_PASSWORD=$2
ALLOWED_CONTAINER=$3
BITCOIN_CONTAINER=$4

export RPC_USER RPC_PASSWORD ALLOWED_CONTAINER BITCOIN_CONTAINER

docker-compose up
