#!/bin/bash

# run as: ./run_peanuts.sh FLASK_ENV RPC_USER RPC_PASSWORD RPC_BITCOIN_HOST RPC_CLIENT_HOST
FLASK_ENV=$1
RPC_USER=$2
RPC_PASSWORD=$3
RPC_BITCOIN_HOST=$4
RPC_CLIENT_HOST=$5

export FLASK_ENV RPC_USER RPC_PASSWORD RPC_BITCOIN_HOST RPC_CLIENT_HOST

docker-compose up --force-recreate
