#!/bin/bash

# run as: ./run_peanuts.sh FLASK_ENV RPC_USER RPC_PASSWORD RPC_BITCOIN_HOST
FLASK_ENV=$1
RPC_USER=$2
RPC_PASSWORD=$3
RPC_BITCOIN_HOST=$4

export RPC_USER RPC_PASSWORD RPC_BITCOIN_HOST

docker-compose up
